# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


orbs:
  aws-cli: circleci/aws-cli@2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs: #seyhello, aws-cli exampleの順番でjobが実行される
  aws-cli-example: #jobの名前
    executor: aws-cli/default #実行元の呼び出し
    steps: #実行したい処理の内容
      - checkout
      - aws-cli/setup: #orbsから引っ張て来てセットアップしている
          aws-access-key-id: AWS_ACCESS_KEY #circle ciのEnvironment variable（環境変数)で設定した名前と同じ
          aws-secret-access-key: AWS_SECRET_ACCESS
          aws-region: aws_default_region #環境変数で定義する
      - run: 
          name: "upload CloudFormation" #cloudformationをAWS CLIで実行させる。
          command: "aws cloudformation create-stack --stack-name testclci --region ap-northeast-1 --template-body file://my-cloudformation-test.yml"
      - run: 
          name: "aws Wait stack"
          command: "aws cloudformation wait stack-create-complete --stack-name testclci"
      - run:
          name: "upload cf-loadbalancer"
          command: "aws cloudformation create-stack --stack-name testcflb --region ap-northeast-1 --template-body file://my-loadbalancer-cf-test.yml"
      - run:
          name: "awslb wait stack"
          command: "aws cloudformation wait stack-create-complete --stack-name testcflb"
          
  ansible:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f4:80:4d:3a:7d:18:d0:5d:4f:18:7a:9c:89:0a:66:30"
      - run: 
          name: "connect SSH Key"
          command: ssh ${USER_NAME}@${HOST_NAME} 

# Invoke jobs via workflows.
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows"
workflows:
  #aws-cli-workflow:
    #jobs: 
      #- aws-cli-example
  ansibe:
    jobs:
      - ansible